### ISSUE TITLE
show SNMP values in Dashboard

### ISSUE THREAD

**Issue by AndreasBrauckmann** [j7126/OctoPrint-Dashboard#162]
Is it possibility to display SNMP values in Dashboard, i have a Power supply and a Microchip TCP / IP Voltmeter & Ammeter for two lamps, Raspberry and a USB hub. 

pi@octopi:~ $ snmpwalk -v2c -c public 192.168.1.2 iso.3.6.1.4.1.17095.3
iso.3.6.1.4.1.17095.3.4.0 = STRING: "5.59" -> (Volt USB Hub)
iso.3.6.1.4.1.17095.3.5.0 = STRING: "5.06" -> (Volt Raspberry)
iso.3.6.1.4.1.17095.3.6.0 = STRING: "9.90" -> (Volt Spots)
iso.3.6.1.4.1.17095.3.7.0 = STRING: "11.03" -> (Volt Light Bar)
iso.3.6.1.4.1.17095.3.8.0 = STRING: "23.5" (Temperature in the top of the case)

![image](https://user-images.githubusercontent.com/54398520/82726000-61c38680-9ce1-11ea-971d-7e0f42ad0c76.png)

![image](https://user-images.githubusercontent.com/54398520/82726023-96cfd900-9ce1-11ea-9ae3-cba03f4a1b7e.png)

http://www.digital-measure.com/html/tcp_voltmeter_v13.html

![image](https://user-images.githubusercontent.com/54398520/82726432-5cb40680-9ce4-11ea-839a-663f33391f1f.png)

4 channel Power supply LM2596

![image](https://user-images.githubusercontent.com/54398520/82835110-5e87f080-9ec3-11ea-891f-023847746ecd.png)
Ikea lack table for prusa:

![image](https://user-images.githubusercontent.com/54398520/82726342-cc75c180-9ce3-11ea-8b85-87bec6361e26.png)

**Comment by StefanCohen** [comment]
Thanks for the feedback. This sounds interesting but I'm not yet sure how to implement this in a generic way. I guess I will need to think about it for a while. How do you imagine the configuration would work given that there may be multiple sensors displaying different types of info? How would they appear on the dashboard in your opinion?

**Comment by AndreasBrauckmann** [comment]
The easiest way would probably be via a file sensor or shell in the enclosure plugin. Simply display the values via a query. I think this is the easiest way to read in all possible values and you are flexible.

![image](https://user-images.githubusercontent.com/54398520/82834071-4bbfec80-9ec0-11ea-8ab0-7643008c2d61.png)

**Comment by StefanCohen** [comment]
Well. I rely on the enclosure plugin for all other sensors (DHT11 for example) and it already supports shell commands. I'm thinking that it would already work to use Enclosure to invoke snmpget and then simply display that sensor in the dashboard. I think that would work without any modifications at all. At least for temperature sensors. I will play with that to begin with and see what I can learn from that.

**Comment by StefanCohen** [comment]
Hmm. Never mind. Enclosure only supports shell comands for outputs. I will have to think about this for a while.

**Comment by StefanCohen** [comment]
And one more thing. I will  have to add permissions to the config as running arbitrary shell commands like this should require admin access.

**Comment by Willmac16** [comment]
With the addition of command widgets you should now be able to do this.

**Comment by AndreasBrauckmann** [comment]
Sorry for delay ... great Work Stefan, thanks a lot of.
