### ISSUE TITLE
Webcam Stream breaks when using Dashboard Plugin

### ISSUE THREAD

**Issue by anupchavda1** [j7126/OctoPrint-Dashboard#170]
Have a RPi 4 (16gb) and have been using it for some time with latest updated Octoprint. 
Have had the Webcam working consistently from day 1 (on the Control Tab as well as Octolapse.

Configuration on OctoPrint for the Webcam and Timelapse page: Enable Webcam is checked and Stream URL is `/webcam/?action=stream`

Installed Dashboard on 2 different Octoprint instances and it immediately breaks ALL webcam streams (Control Page, Dashboard Page, Octolapse etc). Uninstalling Dashboard brings the feed back.

Any ideas?

**Comment by StefanCohen** [comment]
Thanks for the feedback. 

That seems strange. I have the same setup here and it works fine. Do you see any errors in the Octoprint log or in the javascript console of your browser?

**Comment by StefanCohen** [comment]
@Willmac16 That seems unrelated as OPs issue was reported prior to the release of 1.13.0 that included multicam support. @CynanX Do you have any idea what could cause this issue?

**Comment by anupchavda1** [comment]
It’s weird. It’s now working, BUT only on the dashboard. My “control” tab stays on the getting stream for a few mins and then shaves to unable to get stream

**Comment by CynanX** [comment]
Afraid not.

The second camera is selected by default on the dashboard due to a quirk. There are icons on the top right of the stream where you can switch the streams... they are black and perhaps to faint to see on your system?

**Comment by Willmac16** [comment]
Yup, I can faintly make them out now. Would it be possible to make a dark theme friendly version of them since the rest of the plugin works so well with the dark theme?

**Comment by StefanCohen** [comment]
I’ll look at it.

**Comment by Willmac16** [comment]
I think adding `filter: contrast(0);` to .cameraStreamIcon and slightly increasing the opacity does the trick.

**Comment by StefanCohen** [comment]
Thanks. I'll look at the PR once I'm done with a small experiment.

**Comment by StefanCohen** [comment]
That PR looks good. Merged and ready for v.1.14.0

**Comment by j7126** [comment]
can this be closed @StefanCohen
