### ISSUE TITLE
[Bug] Loose camera configuration & Dashboard camera selection problem

### ISSUE THREAD

**Issue by courtpl** [j7126/OctoPrint-Dashboard#174]
IIt seems a problem between the Dashboard and Multicam pluggin

In Multicam the button name are inverted and the camera configuration reset as defaut camera path for all camera.

In dashboard, The second camera is displayed instead of the default camera.
The camera button selection are displayed under the video, it's not possible to click on.

The problem appear after each reboot
Il have reinstalled the Dashboard version 1.12.2 and it works fine, but i can't use the new feature

RBI 3b+
OctoPrint: 1.4.0
MultiCam (0.2.6)
Dashboard (1.13.0)

**Comment by StefanCohen** [comment]
Thanks for the feedback. I'll take a look.

**Comment by StefanCohen** [comment]
@CynanX I found the problem. It was in the onBeforeBinding method.

It looked like this: 

`self.multicam_profiles(self.settingsViewModel.settings.plugins.multicam.multicam_profiles().reverse());`

That reversed the actual multicam plugin settings to be reversed while I assume that you intended the Dashboards internal self.multicam_profiles to be reversed. So I changed it to:

```
self.multicam_profiles(self.settingsViewModel.settings.plugins.multicam.multicam_profiles());
self.multicam_profiles.reverse();
```

Does that look right to you? It works fine in my tests and stops Dashboard from interfering with the multicam plugin settings. It still doesn't prevent the last cam stream from loading first in the Dashboard but I'll take a look at that next.

**Comment by CynanX** [comment]
Sweet!

Coming from Java I thought it was immutable. Hmm.. need to look into Python unit tests 😀

**Comment by CynanX** [comment]
PS. The last stream becoming active seems to be because the onClick method in the HTML seems to be processed upon load.

**Comment by StefanCohen** [comment]
Ah. I can take a look at that. One thing that still bugs me is that the wrong camera button in the control tab is selected while the right (default) stream is loaded (after my fix). It could be related to the onClick event firing on the wrong viewModel of course.... Hmm. I need to debug this.

**Comment by StefanCohen** [comment]
I tried removing `, click: function(){$parent.webcamState( $index()+1 );}` from the icon data binding and it still loads the last stream by default so it seems unrelated to the onClick event firing on load. Very strange.

**Comment by courtpl** [comment]
Allways the same problen, even after installation of the last version 1.15.0.
Also after some minutes of usage, the server become totally busy.

I have reinstall the version 1.12.2

**Comment by courtpl** [comment]
I have installed the las 1.15 version, but the problem is always the same.
It appear, the server became instable after some minutes of usage.

I have perform a rollback to the version 1.12.2, back to normal.

**Comment by gneu42** [comment]
Hi,
It seems that I have the same problem.
I upgrade multicam and dashboard plugin from 1.11.0 to 1.15.0, Everything looks ok. The next day I restart the printer, and no more second camera, but could access them on my browser. It and the camera seems to have been inverted in octoprint. My original default camera was a raspicam and my second was USBC920, now the default is USB920 and the second one is raspicam. In multicam, both show the same URL : http://192.168.1.183/webcam/?action=stream. No more webcamd2 and the name are inverted.
I can't change the URL of the first one wich is now USB920. I would like to rollback to 1.12.2, but don't have it since I went from 1.11 to 1.15.
Does anyone knows how I can get 1.12.2 on my PI ?

Regards Gérard

**Comment by Willmac16** [comment]
Hi there. I am actively working on a fix/replacement of the multiple camera functionality, and I believe you can install an earlier version by using the install url with "master" replaced with the release number.

**Comment by StefanCohen** [comment]
There is a wiki page describing how to install earlier versions here: https://github.com/j7126/OctoPrint-Dashboard/wiki/Install-an-older-version-of-the-plugin

**Comment by gneu42** [comment]
Thank you for the info. I rollback to 1.13.0. And it seems better than 1.15.0.
- Both cameras are working ok.
- The order of the cameras on the multicam setup and control tab are back to normal.
- The button on my small touch screen using touchUI have an icon showing a camera, while with 1.15.0 they were just white squares.
I'll wait until tomorrow to see if it is stable.

Regards
Gérard

**Comment by Willmac16** [comment]
I've pushed a commit to the development branch that adds multiple camera support to dashboard without using Multicam.

**Comment by gneu42** [comment]
After the rollback of yesterday to 1.13.0, everythink looked ok, but this morning when I restart the printer, the camera were inverted in multicam, and both pointing to webcamd2 !!!

**Comment by j7126** [comment]
this will be fixed in the next release

**Comment by j7126** [comment]
should be fixed in 1.15.1

**Comment by gneu42** [comment]
I installed 1.15.1, and the camera selector buttons are gone. Only the first camera is displayed !!!

**Comment by j7126** [comment]
you have to add the cameras in the dashboard settings, it no longer gets them from the multicam plugin @gneu42

**Comment by gneu42** [comment]
Ok, Now it is working well.

Great job.

Thank you
