### ISSUE TITLE
Webcam panel doesn't resize in smaller screens when in full screen mode / full browser

### ISSUE THREAD

**Issue by mmoraes80** [j7126/OctoPrint-Dashboard#192]
**Describe the bug**
When accessing OctoPrint on a tablet the webcam window doesn't properly resize and covers part of the dashboard panel making it impossible to access the Camera, Full Screen,  Full Browser Window buttons, and some of the icons.

**To Reproduce**
Open Octoprint using a tablet and switch it fo full-screen mode.

**Expected behavior**
The camera panel should resize itself.

**Screenshots**
Not available at this moment.

**Desktop (please complete the following information):**
 - Fire HD7 tablet
 - Silk Browser (chrome based browser)

**Comment by DylanCDuke** [comment]
I second this. 

Seen on desktop, and I've tried changing the camera resolution and aspect ratio on my /boot/octopi.txt. Mine isn't covering the dashboard information, but is instead running off the bottom of the screen.

![image](https://user-images.githubusercontent.com/10234197/89584614-fa0dd980-d801-11ea-9872-ff9b428663ba.png)

**Comment by j7126** [comment]
I am working on this. should be ready in a couple weeks

**Comment by j7126** [comment]
Fixed, these screenshots were taken on my phone

![Screenshot_20201023-195126](https://user-images.githubusercontent.com/35882868/96989556-37fcdd00-1569-11eb-95ab-5e1a45f0b9c6.png)
![Screenshot_20201023-195234](https://user-images.githubusercontent.com/35882868/96989639-55ca4200-1569-11eb-99e9-9b003c81baa2.png)
Should be ready for next release
