### ISSUE TITLE
Layer Graph Showing a Horizontal Scrollbar

### ISSUE THREAD

**Issue by pcgames3112** [j7126/OctoPrint-Dashboard#194]
**Describe the bug**
I currently have two instances of Octoprint running on two separate Raspberry Pi 3B+
Both are running the identical setup (One was installed from a backup of the other).

The instance with the problems is connected to a printer with two extruders. The working one only has a single extruder.

On the original installation everything works as expected. On the clone the layer graph is showing a horizontal scrollbar, which makes it impossible to use.
Here are a screenshot of how it looks and what the Chrome developer tools show:
Interface: https://puu.sh/Glkmt.png
Devtools: https://puu.sh/Glkpd.png (on the working printer the width is always at 100%)

**To Reproduce**
1. Go to the Dashboard pane during any print in Chrome or Firefox

**Expected behavior**
Show the entire graph without a scrollbar like on my other printer.
Screenshot of the working printer: https://puu.sh/Glksw.png

**OctoPrint server and Plugins:**
 - Platform: RPi 3b+
 - OS and version: Raspberry Pi OS Buster
 - OctoPrint version: 1.4.2
 - OctoPi version: n/a
 - Dashboard version: 1.14.0
 - DisplayLayerProgress version: 1.23.0

**Desktop (please complete the following information):**
 - OS and version: Windows 8.1
 - Browser and version: Chrome 84.0.4147.135, Firefox 79.0

**Comment by Willmac16** [comment]
A layer duration graph view mode option has been added to the settings (with a non scrolling version as the default).
