### ISSUE TITLE
rearrange dash when webcam turned off

### ISSUE THREAD

**Issue by DrivenDemon** [j7126/OctoPrint-Dashboard#209]
It would awesome if when the webcam is turned off from the dashboard the other info scaled to take the place of the open space. As of right now when the cam is turned off all of the info stays on the left side of the screen while in full screen mode. I would like to have all of the info take up the rest of the screen. 

The reason for this is I have a small touch screen as a monitor and there is a lot of open space on the right. (its right next to the printer) [see below]
<img width="503" alt="octoprint" src="https://user-images.githubusercontent.com/36494281/94693178-63413300-0301-11eb-94f3-ffaf6682f0d4.png">

**Comment by j7126** [comment]
Released 1.16.0
