### ISSUE TITLE
Add print time gauge

### ISSUE THREAD

**Issue by StefanCohen** [j7126/OctoPrint-Dashboard#211]
The gauges shown during a print job includes "Job" and "Layer". The current Job gauge is really only displaying the bytes sent vs the size of the file size. 

It would be nice to rename the current "Job" gauge to "Gcode" and add a third gauge named "Time" that displays the time spent vs the estimated time in %. The reason is that the Gcode gauge is rarely linear while the proposed Time gauge should be (at least with PTG installed). A third gauge would also result in a more symmetrical UI for most configurations and it would be easier to know the time progress at a glance compared to reading the value down in the ETA widget

Something like this:

![Screenshot 2020-10-01 at 13 21 02](https://user-images.githubusercontent.com/33824565/94803821-2f8e0800-03ea-11eb-8bf7-853f45954024.png)

An equivalent bar chart needs to be added of course.

**Comment by j7126** [comment]
Ready for next release

**Comment by StefanCohen** [comment]
The Time Gauge sometimes (but not always) shows the percentage as NaN when starting a print. I guess the timestamps needs to be initialised to some sane values on print start.

**Comment by j7126** [comment]
I thought I already fixed that
are you running the latest dev commit?
