### ISSUE TITLE
Accommodate loooong filenames

### ISSUE THREAD

**Issue by xeddog** [j7126/OctoPrint-Dashboard#212]
**Describe the solution you'd like**
When the dashboard is displayed, long filenames continue outside of the box. As shown in the attached sreenshot.  

![image](https://user-images.githubusercontent.com/8324160/95004494-bb499500-05a0-11eb-9b5c-f0acafa92803.png)

Perhaps consider reducing the fontsize on long filenames, and/or wrap to two lines.

**Comment by StefanCohen** [comment]
The Dashboard already supports reducing the fontsize on long filenames but It looks like minSize:5 in the following code in dashboard.js is a bit too big fontsize for resizing some really long filenames properly. Changing it to 2 will accommodate at least 80 chars.

`self.fitties = fitty('#fileInfo', { minSize: 5, maxSize: 20 });`

It is of course not viable to keep scaling down the font like this forever so some method to either wrap or truncate would be preferred.

**Comment by KenLucke** [comment]
LOL, someone was complaining about LONG filenames?

Accommodate this :)

![Uploading CR-10 v2 (Yellow) LAN [OctoPrint] - 0% 2020-10-08 14-40-07.jpg…]()
