### ISSUE TITLE
Colors changed after update to 1.15.0 (with themeify plugin)

### ISSUE THREAD

**Issue by ochm** [j7126/OctoPrint-Dashboard#213]
Before update all normal texts (for example normal CPU temperature) were in blue color.
After upgrade, the texts inherited orange color from different parts, for example from headings (Discoranged theme) 
Now the high temperature of CPU is not visualised.
Without Themeify plugin are colors OK, but white background is boring.

**To Reproduce**
1. use Themeify plugin with Discorange theme
2. check colors on Dashboard
3. upgrade to Octoprint Dashboard 1.15.0
4. Colors are now different

**Expected behavior**
No color schenme change, the same colors like in previous version of Dashboard.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/47606742/95017769-9cf49f80-065b-11eb-9417-783d62cad2f5.JPG)

Bargraphs and all texts are unwantedly in orange:
![screenshot2](https://user-images.githubusercontent.com/47606742/95018187-610f0980-065e-11eb-9a46-e45bd86d846c.JPG)

**OctoPrint server and Plugins:**
 - PlatformRPi 4
 - OS and version: Raspbian Linux 10
 - OctoPrint version: OctoPrint 1.4.2 
 - OctoPi version:  0.17.0
 - DisplayLayerProgress version 1.23.3

**Desktop (please complete the following information):**
 - OS and version: W10
 - Browser and version Chrome, FF ESR, both in latest version

**Comment by Willmac16** [comment]
I have added a setting in the latest commit on the development branch. It should be ready for next release.
