### ISSUE TITLE
detect missing GCODE Viewer viewModel

### ISSUE THREAD

**Issue by StefanCohen** [j7126/OctoPrint-Dashboard#218]
Whenever a user disables the GCODE Viewer, the Dashboard Viewmodel fails to bind and the frontend crashes halfway thru rendering. This is the most frequently reported issue and users have no way of detecting the error unless they open the browser console.

Solution: detect the issue before binding, log the error and notify the user via the ui (pNotify). Optionaly, also disable the layer gauge and data binding until the GCODE viewer has been enabled to allow the rest of the dashboard to work.

See here for an example of a ticket: https://github.com/j7126/OctoPrint-Dashboard/issues/17

This should be doable by registering the gcodeViewModel as optional in the viewmodel configuration. It should in theory then be null unless it has bound successfully. I have tried this in the past but I seem to remember that it didn't work as expected at the time. It is quite possible that this has been fixed since then, so give it a try if you want to.

**Comment by Willmac16** [comment]
Additionally, it would be nice to have behavior to detect if a GCode file is not being automatically visualized due its size.

**Comment by Willmac16** [comment]
I'm going to close this issue because I think it would be better to work on getting the data from another source than to work on improving this method.
