### ISSUE TITLE
The layer timing graph doesn't adjust the grid interval as the number of layers increases

### ISSUE THREAD

**Issue by StarNamer** [j7126/OctoPrint-Dashboard#222]
**Describe the bug**
I remember looking at the code in the past and the layer timing graph had some logic which meant that as the number of layers increased the grid spacing was also increased. So for the first 10 layers the spacing would be 1, but when it was at layer 150, the spacing would be 15 or more. This change seems to have been lost, possibly during the upgrade to Python 3.

**To Reproduce**
Print anything with a few hundred layers.

**Expected behavior**
As the number of layers graphed increases, the spacing is increased so the labels are clear.

**Actual behavior**
Labels are all mashed together and hence cannot be read.

**Screenshots**
![image](https://user-images.githubusercontent.com/1997874/95621991-86d74c80-0a6a-11eb-9f4f-0b022e11048f.png)

**OctoPrint server and Plugins:**
 - Platform: RPi 3b+
 - OS and version: Raspbian (latest)
 - OctoPrint version: 1.4.2
 - OctoPi version: 0.17.0
 - Dashboard version: 1.15.1
 - DisplayLayerProgress version: 1.24.0

**Desktop (please complete the following information):**
 - OS and version: Windows 10
 - Browser and version:  Chrome 85.0.4183.121

**Comment by Willmac16** [comment]
I added the feature back in. It will be in the next release.
