### ISSUE TITLE
Graph and Gouges not displayed 

### ISSUE THREAD

**Issue by elstak80** [j7126/OctoPrint-Dashboard#223]
**Describe the bug**
The dash board only show hotend-bed-fan gouges. I try to activate/disactivate few times all the options but nothing change.

Story:
I meet an issue with dashboard, i seen all gouge at "100%", with no graph and a message that inform about the unavailability of info prom diplaylayerprogress. BNo way to have it back working, install/uninstall...clean data... nothing

So i took the time to re-install octoprint, i migrate to py3 and install all the plugins but not i seen no gouges/graphs 

**Expected behavior**
i want to see all the gouges/graphs as before 

**Screenshots**
https://prnt.sc/ux1f3j
https://prnt.sc/ux1fyv

**Files (please attach the following Files or screenshots when applicable):**
 
https://www.udrop.com/13L3/octoprint.log
https://www.udrop.com/13L2/plugin_DisplayLayerProgress_events.log

**OctoPrint server and Plugins:**
 - Platform: RPi 3b+
 - OctoPrint version: 1.4.2
 - OctoPi version: 0.17.0
 - Dashboard version: 1.15.1
 - DisplayLayerProgress version 1.24.0

**Desktop (please complete the following information):**
 - OS and version: Windows 10]
 - Browser and version: last Edge

**Additional context**

**Comment by j7126** [comment]
@elstak80 From the screenshot it looks like you are not running a print. That stuff only shows up when you are actually printing. Please try starting a print and see if it shows up.
