### ISSUE TITLE
Python version in bug report template

### ISSUE THREAD

**Issue by StefanCohen** [j7126/OctoPrint-Dashboard#225]
**Is your feature request related to a problem? Please describe.**
It is sometimes hard to determine what Python version a bug is reported on.

**Describe the solution you'd like**
Add the Python version to the Github bug report template.

**Describe alternatives you've considered**
N/A

**Additional context**

**OctoPrint server and Plugins:**
 - Platform: [e.g. RPi 3b+, Intel x86]
 - OS and version: [e.g. Raspbian Stretch, Ubuntu 18.10, Windows 10]
 - OctoPrint version: [e.g. OctoPrint 1.3.11]
 - OctoPi version: [e.g. OctoPi 0.16.0]
 - Python version [e.g. Python 3.9.0]   
 - Dashboard version [e.g. Dashboard 1.10.1]
 - DisplayLayerProgress version [e.g. 1.14.0]

**Comment by j7126** [comment]
done
