### ISSUE TITLE
Can't switch between 2 cameras

### ISSUE THREAD

**Issue by ProfEngr** [j7126/OctoPrint-Dashboard#227]
Thanks again for the quick resolution for the older Octroprint version.

I got into the settings and set up both of my USB cameras using the URLs from the now-defunct Multicam plugin. I can still only see the default cam in the Control tab (no button to switch between the 2), but when I add the webcam widget to the main tab I get the second stream in an overly-large window for its puny 640x480 res.

Did I miss something obvious?

**Comment by j7126** [comment]
@ProfEngr can you please post a screenshot of the dashboard tab and of the dashboard webcam settings so I can see exactly what you mean

**Comment by ProfEngr** [comment]
OK, I missed the icons for switching on the main tab. The nozzle is still huge for its native resolution though. The other cam is a 1280 so it shows up ok. There are no camera-like icons on the Control tab to swap streams. I couldn't get the entire UI in the shot. Hope these are ok.
Control Tab, no selector icons anywhere that I saw
![Capture1](https://user-images.githubusercontent.com/44645861/96198146-fd1ff700-0f21-11eb-9023-2a75882919fd.PNG)
Main Tab, has selector icons
![Capture2](https://user-images.githubusercontent.com/44645861/96198173-0dd06d00-0f22-11eb-8c46-ec6e1cedf86c.PNG)

**Comment by ProfEngr** [comment]
Oh, settings...
![Capture3](https://user-images.githubusercontent.com/44645861/96198352-96e7a400-0f22-11eb-807b-db88fcd02c18.PNG)

**Comment by j7126** [comment]
The dashboard multi-cam implementation only shows multiple cameras in the dashboard and does not show them in the control tab. 
You will still need to use the multicam plugin if you want multiple cameras in the control tab. 
Regarding the size of the image for your lower resolution camera, you can try playing around with aspect ratio settings to fix this.

**Comment by ProfEngr** [comment]
I'm using the 4:3 for the low res camera.

Wait, I thought the changelog said multicam wasn't compatible anymore. Was that just meaning the Main tab? If it still works w/ Control then we're good as I had that working before.

**Comment by j7126** [comment]
> Was that just meaning the Main tab? 

yes
