### ISSUE TITLE
Webcam flipV enabled only if flipH is enabled too

### ISSUE THREAD

**Issue by lucabartoli** [j7126/OctoPrint-Dashboard#233]
**Describe the bug**
I'm trying to flip the webcam vertically only but seems impossible.
Vertical flip is enabled only if Horizontal flip is enabled too.
Horizontal flip works alone as expected.
Vertical flip doesn't work alone.

**To Reproduce**
1. Go to the plugin's webcam settings
2. Click on edit
3. Enable vertical flip only
4. click done and save
5. The image is not vertically flipped
6. go back to the webcam settings
7. Vertical flip is disabled 

Try again enabling horizontal and vertical flip, it works.

**Expected behavior**
Webcam can be flipped vertically only.

**Screenshots**

**Files (please attach the following Files or screenshots when applicable):**
* Octoprint.log
* Browser console log
* gcode file that can be used to reproduce the problem

**OctoPrint server and Plugins:**
 - Platform: RPi 3b+
 - OS and version: Raspbian 10
 - OctoPrint version: 1.4.2
 - OctoPi version: 0.17.0
 - Python version Python 2.7
 - Dashboard version 1.15.2
 - DisplayLayerProgress version 1.24.0

**Desktop (please complete the following information):**
 - OS and version: Win 10
 - Browser and version Chrome latest

**Comment by j7126** [comment]
Hi @lucabartoli 

I have tested this on my octopi instance and can't seem to reproduce this behavior. 

Can you please try restarting your OctoPrint server and clearing your browser cache and cookies, and see if that helps the problem. 

Can you also try disabling dashboard multi camera and set vertical flip in the default octoprint webcam, to see if that flip gets shown by dashboard.

**Comment by j7126** [comment]
Can you please also include your logs

**Comment by lucabartoli** [comment]
I tried clearing the cache and restarting octoprint, but didn't solve the issue.

These are the screenshots I forgot to upload before:
Setting webcam flip
![octopi local__](https://user-images.githubusercontent.com/3965942/98519078-8f40c400-2270-11eb-8f79-44ab88fe52d8.png)

The webcam is still reversed
![octopi local__ (1)](https://user-images.githubusercontent.com/3965942/98519171-abdcfc00-2270-11eb-928f-334aff13c710.png)

Going back to settings, check mark disappeared
![octopi local__ (2)](https://user-images.githubusercontent.com/3965942/98519210-bb5c4500-2270-11eb-9c19-9fe0e82cf8be.png)


I updated to python 3 in the meantime, trying to solve the issue.
Now the webcam works, but I can't use the "toggle webcam" button. If I press it, the webcam disappears (as expected) and toggle webcam button doesn't work anymore (seems not having effect).
Reloading the page always works to make the webcam coming back.

**Comment by j7126** [comment]
Can you please upload octoprint's log file and also check if there are any errors in the browser console.

**Comment by lucabartoli** [comment]
[octoprint.log](https://github.com/j7126/OctoPrint-Dashboard/files/5510772/octoprint.log)

And this is the console
![image](https://user-images.githubusercontent.com/3965942/98546783-844d5a00-2297-11eb-9272-4f42e446ce27.png)

**Comment by Willmac16** [comment]
Do you have Dashboard multiple camera support enabled?
<img width="561" alt="image" src="https://user-images.githubusercontent.com/27445690/98602368-30da0c80-2295-11eb-8306-b222caed8bb3.png">

**Comment by Willmac16** [comment]
It looks like I fixed the original bug you reported in 1.16, and j7126 fixed the toggle webcam button bug.

**Comment by j7126** [comment]
1.16.2 released

**Comment by lucabartoli** [comment]
My multiple camera support was disabled, but the update fixed the button!
Kudo to you for the great and instant support! I really appreciate your effort
