### ISSUE TITLE
Understanding of the function - Next Filament Change

### ISSUE THREAD

**Issue by OliPrint** [j7126/OctoPrint-Dashboard#240]
I use your wonderful PlugIn - Octoprint Dashboard, and I would need some help in understanding the function of the displayed Icon of - Next Filament Change.

Am I right, that it will be function like, based on the so far used length of this Spool/Filmament, and knowing the full length, the remaining length will be displayed?

What is the basis for this information? Is it based on a specific add. PlugIn? If yes, how do I integrate/link them together?

Many thanks in advance for your help
Oliver

**Comment by j7126** [comment]
The next filament change widget displays the time until the next M600 filament change in the print. 

Some slicers have a feature such as pause at height or change filament at height, which allow you to have the print pause so you can change the filament at a certain point in the print to allow for multi-color prints. This widget shows the amount of time until the next occurrence of this. The idea of this widget is to allow you to see when you will need to come to your printer and change the filament to the different color. 

The data for this widget is sourced automatically from the display layer progress plugin, which is required by dashboard and you probably already have installed if you have dashboard working. 

Please bear in mind that currently this widget may not work for all slicers that provide the filament change feature.

**Comment by j7126** [comment]
See https://marlinfw.org/docs/gcode/M600.html for details on the M600

**Comment by OliPrint** [comment]
Many thanks for the information and the implied clarification.
A complete misinterpration on my side.
thx 
Oliver
