### ISSUE TITLE
Percent Complete by Height

### ISSUE THREAD

**Issue by ChuckRider** [j7126/OctoPrint-Dashboard#245]
Add a circle graph to the row with the % complete ones that displays the % of height complete.  It is would be interesting on some of the prints to see that the print is, for example, 80% complete by time/gcode but only 40% of the height has been completed.  I can derive these by reading the numbers of current layer vs total layers but it would be neat to see it visually as another circle widget.

**Comment by j7126** [comment]
Ready for next release

**Comment by ChuckRider** [comment]
Looks great, thank you!
