### ISSUE TITLE
Re-arrange items based on preferences.

### ISSUE THREAD

**Issue by monukoshy** [j7126/OctoPrint-Dashboard#246]
Requesting an option to re-arrange items based on preferences, for eg:- right now the webcam sits in the bottom of the page if all the other functions are enabled, and you have to scroll down to see the webcam.

**Comment by StefanCohen** [comment]
One of the goals for V2 is the possibility to freely rearrange the dashboard.

**Comment by j7126** [comment]
Closing this to keep all v2 discussion to #249
