### ISSUE TITLE
Very large progress bars in full screen mode

### ISSUE THREAD

**Issue by TheLion** [j7126/OctoPrint-Dashboard#256]
Hi,

In both browser-full-screen mode and full-screen mode, the progress bars are very large, which causes some information to not be visible.

I tested on separate machines with both Firefox and Chrome and the behavior is the same on all.

See screenshot for more info
[Screenshot_full_screen](https://user-images.githubusercontent.com/3755011/107848981-588ec280-6df8-11eb-8751-743dc4197fd3.JPG)

When switching off the webcam, the information appears, but the progress bars are still very large.
[Screenshot_full_screen_webcam_off](https://user-images.githubusercontent.com/3755011/107849020-a4416c00-6df8-11eb-981b-e5c449179185.JPG)

When using circles in stead of progress bars, it looks just fine.
[Screenshot_full_screen_circles](https://user-images.githubusercontent.com/3755011/107849189-e919d280-6df9-11eb-9c5a-92f7d1199232.JPG)

Also disabled Themeify colors, but that didn't make a difference.

Is this as designed, or should the progress bars be smaller?

**Comment by j7126** [comment]
Hi @TheLion. Thanks for reporting this, I have made a fix and it will be included in the next release.
