### ISSUE TITLE
Enclosure Plugin Temperature Controller Widget

### ISSUE THREAD

**Issue by wickedbeernut** [j7126/OctoPrint-Dashboard#257]
The Dashboard plugin currently supports Enclosure plugin rpi_inputs of type temperature_sensor (e.g., enclosureViewModel.rpi_inputs_temperature_sensors()).  If enabled, the Dashboard plugin displays a widget with the actual temperature and humidity.

The Enclosure plugin also supports rpi_outputs of type temp_hum_control.  In addition to the actual temperature (and optionally actual humidity), the temp_hum_control output also includes a target temperature (temp_ctr_max_temp).

Please add support to allow the Enclosure plugin (and other plugins) to add a widget to the dashboard with the actual temperature, actual humidity and target temperature.

![abc](https://user-images.githubusercontent.com/47407361/107980019-ce239b80-6f7c-11eb-895e-4efe26081ac7.png)
![image](https://user-images.githubusercontent.com/47407361/108629217-2c88c800-741c-11eb-8449-d923a1c5cb0b.png)

**Comment by j7126** [comment]
Yes this will be possible with v2

**Comment by wickedbeernut** [comment]
> @j7126 said, "Yes this will be possible with v2".

Excellent!

I edited the issue to read more like a feature request than a question.

**Comment by j7126** [comment]
The thing with v2 will be that almost anything will be possible, as integrations with other plugins will be more up to that plugin developer. 

There will also be much more freedom for the user to customize widgets, as the idea will be that the user will be able to add a widget, choose it's type (like gauge, text progress bar, button etc.) and then choose a data point or action from OctoPrint or any plugin to apply to that widget.

**Comment by j7126** [comment]
I am closing this issue now as i would like to keep v2 related discussion in #249 for now.

**Comment by wickedbeernut** [comment]
@j7126, I understand with v2 anything will be possible, but I just wanted to share one more mockup.

This is what my six temperature controllers (heaters and coolers / fans) corresponding to three filament dryers actually look like in the Enclosure plugin (this is not a mockup),

![image](https://user-images.githubusercontent.com/47407361/110721150-1e34fd00-81cd-11eb-9d09-64c9ac7ccf61.png)

I plan to leverage the Dashboard plugin v2 to display the six temperature controllers as,

![image](https://user-images.githubusercontent.com/47407361/110721034-df9f4280-81cc-11eb-8db7-8da4f12c2ae7.png)
