### ISSUE TITLE
Webcam state is not honored when moving away from the dashboard

### ISSUE THREAD

**Issue by samwiseg0** [j7126/OctoPrint-Dashboard#263]
**Describe the bug**
In versions prior to 1.18.0, when moving to another tab and then moving back to dashboard the webcam state was honored. Since the changes to how the webcam is loaded. This is no longer honored. This also seems to be a problem when moving away from the browser tab as well. 

Additionally, this may fall under another request/feature request, but it would be nice if the state is also pervasive on page reloads as well. 

**To Reproduce**
1. Load octoprint UX
2. Hide the webcam from the dashboard
3. Move to another browser tab or octoprint tab
4. Move back to the dashboard tab
5. Observe that the webcam is now visible. 

**Expected behavior**
The state of the webcam should be honored and not changed when moving to other browser tabs and/or octoprint tabs. 

**Screenshots**

<img width="537" alt="Screen Shot 2021-03-15 at 10 28 06 PM" src="https://user-images.githubusercontent.com/2241731/111247110-d7387480-85dd-11eb-855d-76275e44c364.png">

**Files (please attach the following Files or screenshots when applicable):**
NA

**OctoPrint server and Plugins:**
 - Platform: **Rpi 4B**
 - OS and version: **Raspbian**
 - OctoPrint version: **OctoPrint 1.5.3**
 - OctoPi version: **OctoPi 0.18.0**
 - Python version **Python 3.9.0**
 - Dashboard version **Dashboard 1.18.0**
 - DisplayLayerProgress version **1.25.4**

**Desktop (please complete the following information):**
 - OS and version: **MacOS**
 - **Chrome Version 89.0.4389.82 (Official Build) (x86_64)**, **Safari Version 14.0.3 (16610.4.3.1.7)**

**Logs**
NA

**Additional context**
NA

**Comment by Willmac16** [comment]
Thanks for reporting this. I have fixed the issue and you can try out the fixes by installing with `https://github.com/j7126/OctoPrint-Dashboard/archive/development.zip`

**Comment by samwiseg0** [comment]
Confirmed that is works correctly now! Thanks for fixing it so fast!

**Comment by Willmac16** [comment]
Fix was released with 1.18.1
