### ISSUE TITLE
Slow/laggy octoprint ui after update of this plugin to v1.18

### ISSUE THREAD

**Issue by rmeissn** [j7126/OctoPrint-Dashboard#264]
**Describe the bug**
After an update of the plugin to v1.18.0 the whole web ui of octoprint became ultra slow/laggy. I noticed a similar behaviour (but not nearly as bad!) when opening the control tab and viewing the webcam feed, for which I increased the resolution (1280x960 at 15fps, raspi 5MP cam).
Is it possible that, even though I have not enabled the webcam part of the dashboard plugin, a webcam stream is activated and processed, but not visible?

**To Reproduce**
Load the web ui

**Expected behavior**
Same performance as with v1.17, which worked perfectly fine.

**Files (please attach the following Files or screenshots when applicable):**
* [octoprint.log](https://github.com/j7126/OctoPrint-Dashboard/files/6147536/octoprint.log)
* [browser-console-export-2021-3-16_10-10-53.txt](https://github.com/j7126/OctoPrint-Dashboard/files/6147541/browser-console-export-2021-3-16_10-10-53.txt)

**OctoPrint server and Plugins:**
 - Platform: RPi 4b
 - OS and version: OctoPi 0.18.0
 - OctoPi version: OctoPi 0.18.0
 - Python version: Python 3.7.3
 - Dashboard version: Dashboard 1.18.0
 - DisplayLayerProgress version: 1.25.4

**Desktop (please complete the following information):**
 - OS and version: Fedora 33
 - Browser and version: Firefox 86.0.1

**Additional context**
Sometimes the web ui loads, is completely unresponsive and changes to a loading circle with grey background after some minutes.

**Comment by Willmac16** [comment]
Fix released with 1.18.1
