### ISSUE TITLE
Make CSS safe

### ISSUE THREAD

**Issue by LazeMSS** [j7126/OctoPrint-Dashboard#269]
**Is your feature request related to a problem? Please describe.**
Could you consider making the CSS safe ie avoid using generic assigns for charts and generic classnames (.target). Basically prefixing the css with any containers you elements are inside. exampl <div class="OctoPrint-Dashboard><a class="target"></a></div>. Making the css like: OctoPrint-Dashboard.target would avoid conflicts with other plugins etc.

**Comment by Willmac16** [comment]
I made some improvements, and they should come through with the next release.
