### ISSUE TITLE
FR: ETA should include date

### ISSUE THREAD

**Issue by gjsmo** [j7126/OctoPrint-Dashboard#270]
**Is your feature request related to a problem? Please describe.**
ETA is very helpful, but only has time and not date. For prints over 24 hours this can be confusing.

**Describe the solution you'd like**
If the print is estimated to take longer than 24 hours, the ETA should show a date 

**Describe alternatives you've considered**
It's always possible to calculate ETA manually from "estimated time left" but this makes the ETA indicator kinda useless.

**Comment by j7126** [comment]
Ready for 1.18.3

![image](https://user-images.githubusercontent.com/35882868/124106169-4d86b700-daa7-11eb-8084-896a219af540.png)
