### ISSUE TITLE
 Possibility to change colors without themiefy

### ISSUE THREAD

**Issue by philder** [j7126/OctoPrint-Dashboard#271]
Is it possible to add a feature that allows us to change the colors of gauges and the text without needing themify (which I also think is not working)? As a user of the UI Customizer plugin, I would like to use this dashboard with the colors based on my theme.

Thank you!

**Comment by Willmac16** [comment]
It sounds like the best solution here would be to have Dashboard also match ui-customizer color schemes and make sure that css theming plugins properly apply to dashboard if possible.

**Comment by Willmac16** [comment]
![image](https://user-images.githubusercontent.com/27445690/118376821-36cfe380-b57f-11eb-8f8c-03f8e79118ff.png)
I got UICustomizer support working (and cleaned up some minor theming glitches), but I am adding this alongside other changes for 1.19. I will let you know when a working early version of 1.19 is ready to be tested.

**Comment by Willmac16** [comment]
@philder I was able to move the code over to the dev branch, so you can install with the url `https://github.com/j7126/OctoPrint-Dashboard/archive/refs/heads/development.zip` and try it out.

**Comment by j7126** [comment]
currently as far as i can tell, this method only works with the red night theme

**Comment by j7126** [comment]
I have submitted a PR to UI Customizer to add css variable support to a few more themes.

LazeMSS/OctoPrint-UICustomizerThemes#19

**Comment by j7126** [comment]
Theming from UI Customizer themes is included as of 1.18.3

It would probably be a good idea to add a setting for custom colors as well at some point to be honest.
