### ISSUE TITLE
Dashboard not showing layer progress

### ISSUE THREAD

**Issue by Doormat1** [j7126/OctoPrint-Dashboard#278]
Im not sure what the issue is, whether its a slicer issue or a Dashboard issue, but as you can see I dont get any layer progress features on dashboard. 
![Dashboard view](https://user-images.githubusercontent.com/68517771/119274606-a80b3880-bc08-11eb-8ac6-cc68029ab070.png)

**Comment by Willmac16** [comment]
@Doormat1 What version of Dashboard is this? And do you have Display Layer Progress installed?

**Comment by Doormat1** [comment]
I have display layer progress installed and it is 1.18.2

**Comment by Willmac16** [comment]
@Doormat1 Can you share your octoprint.log and a browser log

**Comment by Doormat1** [comment]
Here is the octoprint log. Not sure how to get a browser log

**Comment by Willmac16** [comment]
Can you upload it on GitHub, since it doesn't seem to have gone through.

**Comment by Doormat1** [comment]
[octoprint.log](https://github.com/j7126/OctoPrint-Dashboard/files/6534071/octoprint.log
Here it is

**Comment by Doormat1** [comment]
I guess Dashboard relies on Display Layer Progress which seems to require Print time genius to work properly, as Ive run M503 on my printer and now Im getting a star next to g code files and Im getting max z height.

**Comment by Willmac16** [comment]
Dashboard is moving away from requiring Display layer progress (so the max height would work without either of them), but dashboard will probably continue to benefit from print time genius since gcode simulation of that level is out of scope for dashboard.

**Comment by Doormat1** [comment]
I had analysis set to only when Idle, have changed it to always now and PTG seems to be working fine as dose Dashboard now.
