### ISSUE TITLE
Can’t configured dashboard and status bar don’t Show Progress 

### ISSUE THREAD

**Issue by ItsDominator** [j7126/OctoPrint-Dashboard#281]
Hi all, 

Want to check the raspi temperature today but don’t see it on dashboard. Also the progress in the status bar in top of the side is not shown as before. 

If I deactivate the dashboard plugin, the Progress stays in the status bar. 

I deinstalled the dashboard plugin and install it complete new, same problems. 

System and plugins on newest stable version. 

![C200F07C-7072-4B05-B4B7-8EE31B041AB1](https://user-images.githubusercontent.com/69193702/120924506-5ff21880-c6d4-11eb-968b-8df44dd03e14.png)
![3B3B7C67-8AB4-4FD8-A71E-B9DC38417870](https://user-images.githubusercontent.com/69193702/120924508-61234580-c6d4-11eb-8a44-523c7dc7358b.png)
![051B067D-8771-45F8-B928-5033D96886F8](https://user-images.githubusercontent.com/69193702/120924509-61bbdc00-c6d4-11eb-8286-95772b8f61fd.png)
![1DB0AB14-2F63-49B5-B559-8313C3C0E9BD](https://user-images.githubusercontent.com/69193702/120924511-61bbdc00-c6d4-11eb-8f42-362c784b0ec5.png)

**Comment by Willmac16** [comment]
@ItsDominator looks like Dashboard is running into and error and won't properly render. Does this error show up on other devices/browsers? If so please send us a browser log so we can address the issue. Otherwise you would have to attempt to get browser logs off of your iOS decice which may take more effort.

**Comment by ItsDominator** [comment]
After a reboot I can configure the Dashboard again and get the details as before. So I don’t find a issue jet at the Moment. 
thank you!
