### ISSUE TITLE
Widget Settings Missing

### ISSUE THREAD

**Issue by Xiondewah** [j7126/OctoPrint-Dashboard#282]
Could you give me some examples of what goes into the widget settings fields please?  All I seem to get is an empty box that I can't type anything into and I can't see what to use them for.

Thanks!

**Comment by j7126** [comment]
I am not exactly sure which box you are referring to. Can you send a screenshot of the issue?

**Comment by Xiondewah** [comment]
Sorry - I should have done that!

![image](https://user-images.githubusercontent.com/50043329/122215024-aac51a80-cea2-11eb-810c-e82750a3da0d.png)

**Comment by j7126** [comment]
Well it looks like the settings are missing for some reason. Does this happen to the settings for all the widgets or is it just one of them? 

Can you check for any errors in the browser console and also upload your octoprint.log file?

**Comment by Xiondewah** [comment]
Yes it happens for every widget.

How do I check in the browser console?  Log attached.

[octoprint-2.log](https://github.com/j7126/OctoPrint-Dashboard/files/6662969/octoprint-2.log)

**Comment by j7126** [comment]
You can check the console by right clicking somewhere on the page, then press inspect, then the console tab at the top

**Comment by Xiondewah** [comment]
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (eeprom_marlin.css.map, line 0)
> Selected Element
< <div class="modal-body form-horizontal" data-bind="foreach: settings" style="overflow: auto; max-height: 433px;"></div>

Not sure if that's right or not - but it was an error.

**Comment by j7126** [comment]
What browser are you using, does this happen in other browsers?

**Comment by Xiondewah** [comment]
I'm using Safari on Mac - only browser I have - but I have also checked it on my iPad and it's the same (though obviously that's also safari.

I do have the UI Customizer plugin installed - don't know if that's anything to do with it as there were a couple of glitches on other plugins at one point.

**Comment by Xiondewah** [comment]
I just tried Chrome on my iPad and it’s the same I’m afraid.

**Comment by jbeahan** [comment]
I am also missing the widget settings.  I am trying to add a second webcam to the dashboard.  Any other way to do this until the bug is fixed?  Any information I can provide to assist?

**Comment by jbeahan** [comment]
I went through and disabled all plugins, enabled one at a time, and determined the conflicting plugin in my case was "GCODE System Commands (1.0.1)" by Shawn Bruce

**Comment by j7126** [comment]
@jbeahan that's very helpful. I will look at making a fix sometime later today or tomorrow.

**Comment by j7126** [comment]
Can you please check if the settings for the following widgets show up: 

- progress gauges
- layer duration graph
- filament widget

**Comment by j7126** [comment]
I have released a fix in 1.18.3

**Comment by jbeahan** [comment]
I can confirm this fixed the issue!  Thank you so much for your prompt response!!!!

**Comment by Xiondewah** [comment]
Yes - thanks for the fix :-)

**Comment by Xiondewah** [comment]
Just updated - all working now.  Thanks very much :-)
