### ISSUE TITLE
Display Thumbnail

### ISSUE THREAD

**Issue by Xiondewah** [j7126/OctoPrint-Dashboard#287]
Because I use Dashboard primarily now, I don't have the 'Status' panel open.

As I print with multiple printers and instances of Octoprint, it would be really handy to see a small thumbnail of the print on the dashboard in the same way as it is displayed (with the additional plugins) on the Status panel.

Thanks.

**Comment by Willmac16** [comment]
@Xiondewah can you share what plug-ins you are using to get the thumbnail into the Status bar.

**Comment by Xiondewah** [comment]
Hi - sure - it's Cura Thumbnails - though there is also the Slicer Thumbnails plugin, not sure which is best :-)

**Comment by j7126** [comment]
added in 1.19.0
