### ISSUE TITLE
Feedrate graph stroke too wide

### ISSUE THREAD

**Issue by vajonam** [j7126/OctoPrint-Dashboard#295]
**Versions**
OctoPrint 1.7.2 
Python 3.8.12
Dashboard: 1.18.3

**Describe the bug**
Looks like the feedrate dial graph width is buggered up.

**To Reproduce**

Enable Filament Settings

**Expected behavior**
Graph should like other graphs.

**Screenshots**
![Peek 2021-11-03 17-25](https://user-images.githubusercontent.com/152501/140195516-610838e3-a988-4186-92cc-fc393b1f5b10.gif)

**Comment by vajonam** [comment]
This fixes the problem on Chrome inspector.

![image](https://user-images.githubusercontent.com/152501/140195902-c547f2e9-9cc8-4ebe-8131-d48563715409.png)

**Comment by vajonam** [comment]
https://github.com/j7126/OctoPrint-Dashboard/blob/9b5bff518ab1ff133a5d126574e1457ea9cdd8e3/octoprint_dashboard/templates/dashboard_tab.jinja2#L444

**Comment by j7126** [comment]
Looks like this should be fixed in version 1.19.0

**Comment by vajonam** [comment]
Software updates isn't showing the update yet. Once it does will test and close this. Thanks.
