### ISSUE TITLE
Enclosure monitor remains even when marked disabled in settings

### ISSUE THREAD

**Issue by KenLucke** [j7126/OctoPrint-Dashboard#298]
Dashboard v 1.19.0

**Describe the bug**
Despite the "Enclosure Gauges" being disabled in the settings:
<img width="858" alt="image" src="https://user-images.githubusercontent.com/57936294/140397106-692abe9d-2845-4abc-8cbb-47bd58cc7e77.png">
The gauge still shows up in the main display:
<img width="915" alt="image" src="https://user-images.githubusercontent.com/57936294/140397277-f241a9bf-a703-4afb-8748-9fe25215e518.png">

[octoprint-systeminfo-20211104110256.zip](https://github.com/j7126/OctoPrint-Dashboard/files/7477295/octoprint-systeminfo-20211104110256.zip)

**Comment by KenLucke** [comment]
I was able to remove it by deleting it in this setting panel:

<img width="573" alt="image" src="https://user-images.githubusercontent.com/57936294/140435696-2928c0c6-6a86-48c1-9b5a-7ecdca43cae9.png">

**Comment by j7126** [comment]
You were referring to this one correct?
![image](https://user-images.githubusercontent.com/35882868/140442368-16a664c5-a312-47aa-bb47-0bd81c2e1b98.png)
That is from the command widgets, as you said you removed the command widget, however you could have also disabled the command widgets in general.
Command widgets now have the option to appear as a temperature gauge.
