### ISSUE TITLE
Since update to 1.19.0 dashboard shows wrong fan speed

### ISSUE THREAD

**Issue by JWRu** [j7126/OctoPrint-Dashboard#301]
Dashboard shows 0% although the fan is running at 30%.
Everything was ok with the previous release.

**Comment by vajonam** [comment]
Yup seeing the same.

**Comment by joaquinabian** [comment]
Confirm the same. After last update, the fan shows always as 'Off'

**Comment by balu2609** [comment]
Same here

**Comment by MasterYod4** [comment]
Same here

**Comment by j7126** [comment]
I am working on a fix for this
