### ISSUE TITLE
Octoprint and Dashboard see different total and current layer numbers

### ISSUE THREAD

**Issue by joaquinabian** [j7126/OctoPrint-Dashboard#303]
**Describe the bug**
Octoprint and Dashboard see different total and current layer numbers

**To Reproduce**
1. Start a print in OctoPrint and select the Dashboard tab
2. Number of total layers, and current layers are different in Octoprint/State and on Dashboard.

**Expected behavior**
Expect the same values.

**Screenshots**
Screenshot attached.

![different_layers_octoprint](https://user-images.githubusercontent.com/619491/140558654-479671f8-70c2-4bc5-a280-cfa9d9f7c03c.JPG)

**OctoPrint server and Plugins:**
 - Platform: RPi 3b+
 - OS and version: Octopi 0.18.0
 - OctoPrint version: Octoprint 1.7.2
 - Python version Python 3.7.3
 - Dashboard version 1.19.0

**Desktop (please complete the following information):**
 - OS and version: Windows 10
 - Browser and version chrome 95.0.4638.69 (Official Build) (64-bit)
 - Slicer version Cura 4.11

**Logs** 
OctoPrint log file attached 
[octoprint.log](https://github.com/j7126/OctoPrint-Dashboard/files/7488103/octoprint.log)

**Comment by MasterYod4** [comment]
Same here

**Comment by vajonam** [comment]
Is this fixed? I am running 1.19.3 and still seeing wildly different layer numbers

![image](https://user-images.githubusercontent.com/152501/140662446-03d40108-f712-432b-a7b1-6d5dd506da24.png)

**Comment by vajonam** [comment]
![image](https://user-images.githubusercontent.com/152501/140662464-33711a78-692c-45a3-86c1-f44914296446.png)

**Comment by vajonam** [comment]
342 is the correct number of layers according to the slicer.. is this 1.7.2 issue? @j7126
