### ISSUE TITLE
Format of average Layer time H:mm:ss

### ISSUE THREAD

**Issue by miweimann** [j7126/OctoPrint-Dashboard#310]
since 1.90 the format of average Layer time is no more like h:mm:ss, but is something like seconds? This is not useful, because i have to get an calculator every time, i want to know how long the time is in hours minutes and seconds. 

**Describe the solution you'd like**
Please change the format or give a setting to change it by myself.

**Comment by KixMan28** [comment]
I don't think this should be an "enhancement" as this feature was present in the previous versions. I would rather call it a "bug" in the current version, unless this is the way the plugin owner intended to implement this.

**Comment by miweimann** [comment]
How can i change the label? i am quite new in this.

**Comment by KixMan28** [comment]
@miweimann Why you closed this issue?

**Comment by j7126** [comment]
I will look at fixing

**Comment by KixMan28** [comment]
@j7126 Thank you for having a look at it.

**Comment by brunoherrera** [comment]
still present

**Comment by j7126** [comment]
Sorry I took so long to get to this, the fix will be in the next release.
