### ISSUE TITLE
Alignment/Wrapping issue with Disconnected. 

### ISSUE THREAD

**Issue by vajonam** [j7126/OctoPrint-Dashboard#312]
**Describe the bug**

Alignment issue with the disconnected.  text

![image](https://user-images.githubusercontent.com/152501/140956742-7066ec94-e400-455d-a75a-b64cc6e25a10.png)

**To Reproduce**
Disconnect 

**Expected behavior**
No wrapping of text.

**OctoPrint server and Plugins:**
 - Platform: Intel
 - OS and version: Ubunut 20.04 docker. 
 - OctoPrint version: 1.7.2
 - Python version: 3.8.2
 - Dashboard version: 1.19.3
 

**Desktop (please complete the following information):**
 - OS and version: Linux PopOS 21.04
 - Browser and version: Chrome 95.0.4638.54
 - Slicer version: N/a

**Comment by j7126** [comment]
Should be fixed in the new release
