### ISSUE TITLE
Format of average Layer time H:mm:ss

### ISSUE THREAD

**Issue by miweimann** [j7126/OctoPrint-Dashboard#317]
since 1.90 the format of average Layer time is no more like h:mm:ss, but is something like seconds? This is not useful, because i have to get an calculator every time, i want to know how long the time is in hours minutes and seconds.

Describe the solution you'd like
Please change the format or give a setting to change it by myself.

**Comment by InoxDragoon** [comment]
I, too, have noticed this behavior and would like it reverted.

**Comment by j7126** [comment]
#310 will be in next release.
