### ISSUE TITLE
Tab not selected on Octoprint-Startup (always enters temperature tab)

### ISSUE THREAD

**Issue by Rene1695** [j7126/OctoPrint-Dashboard#323]
Dear all,

i installed the dashboard plugin on my octoprint server. After a reboot, i figured out, that the dashboard tab is on the most left side which shall force octoprint to enter this tab on startup. 

Unfortunately, everytime i connect to my octoprint server, it will always start on the default "temperature" tab from octoprint, which is right next the dashboard tab. Do i have to set a startup tab in the settings? I didnt found any options. 

Additional Informations:
Raspberry Pi Zero V2 running octoprint v 1.7.2
Dashboard Plugin v.1.19.5

![image](https://user-images.githubusercontent.com/71972934/148542762-bd00195e-1e81-4cfe-9361-2eb86e1ed652.png)

**Comment by j7126** [comment]
First thing to try, if you are accessing octoprint from a bookmark, does that bookmark by any chance have `#temp` at the end?
If that is the case then all you would have to do is remove the `#temp` from the bookmark.
If that is not the case, can you please share your octoprint system info bundle

**Comment by Rene1695** [comment]
Removing #temp worked for me, thank you very much! Issue can be closed :)
