### ISSUE TITLE
Dashboard.js totalHeigth fx

### ISSUE THREAD

**Issue by Sekisback** [j7126/OctoPrint-Dashboard#324]
May I am wrong but in Dashboard.js Line 277 the toFixed() should be 2

```
// Height
 if (data.maxZ) { self.totalHeight(Number(data.maxZ).toFixed(1)); }
```

this should be

```
// Height
 if (data.maxZ) { self.totalHeight(Number(data.maxZ).toFixed(2)); }
```

**Comment by j7126** [comment]
Why is that?

**Comment by Sekisback** [comment]
if you work with layer height 0.16 for example, the total height in the dashboard is rounded after the first number.
3 layer in 0.16 will be displayed as 0.5 and should be 0.48

**Comment by j7126** [comment]
ok, will change
