### ISSUE TITLE
Widget for chamber temp is shown although  printer profile does not have chamber temp

### ISSUE THREAD

**Issue by gituemmel01** [j7126/OctoPrint-Dashboard#330]
In the dashboard the widget for chamber temp is always displayed, but in the printer profile (Ender 5) the checkbox for heated chamber temp is not selected. So the widgets shows "NaN" and shoud not be visible.
Plattform Raspberry Pi 4, OctoPrint-Dashboard-1.19.6, OctoPrint 1.7.3

![image](https://user-images.githubusercontent.com/98326443/150804917-8d8e40a1-ee9a-41fe-8294-f640697f3e84.png)

![image](https://user-images.githubusercontent.com/98326443/150804250-1dcfb370-df64-42b0-8172-a83c232d6650.png)

**Comment by ackermannsven** [comment]
Also, when used with a independent dual extruder IDEX setup, the fan speed and chamber temp overlap:

Raspberry Pi 3B, OctoPrint Dashboard 1.19.7, OctoPrint 1.7.3

**Comment by j7126** [comment]
That is in fact a command widget, not the heated chamber widget, as the default "example" command widget is a simulated chamber widget. That should not be visible by default, and it seems that there is something broken with hiding disabled command widgets, which is also causing the overlap issue.

I am working on a fix, but in the meantime a temporary workaround you can use would be to just completely disable command widgets from within dashboard settings.
![image](https://user-images.githubusercontent.com/35882868/151343047-888b7173-c20c-47ed-a46f-e55e8489a648.png)

**Comment by ackermannsven** [comment]
Thanks a lot, this worked for me. I did also try to remove the "simulated chamber", seems also to be fine that way.
