### ISSUE TITLE
[Bug]: Celsius shown on enclosure AM2302 device instead of Farenheit on Dashboard

### ISSUE THREAD

**Issue by shakeandbake017** [j7126/OctoPrint-Dashboard#332]
### The problem

1. I have a AM2302 sensor that detects temp and humidity.  On the enclosure tab, it shows correctly with the Fahrenheit symbol.  On the dashboard page, it shows with the correct temp number but with Celsius instead of Fahrenheit.  Please see attached screenshot.  

### Version of OctoPrint

1.7.3

### Platform

Raspberry Pi 3b

### Operating system running OctoPrint

OctoPi 0.18.0

### Dashboard version

1.19.8

### Python version

3.7.3

### Printer model & used firmware incl. version

Ender 3 Max 

### Browser and version of browser, operating system running browser

Microsoft Edge

### Logs and other files needed for analysis

- [X] Systeminfo Bundle (always include!) See [here](https://community.octoprint.org/t/what-is-a-systeminfo-bundle-and-how-can-i-obtain-one/29887) if you don't know where to find that.
- [X] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### File uploads & additional information

<img width="940" alt="149250102-e94a8660-255d-47a8-90a9-d7322754c637" src="https://user-images.githubusercontent.com/97309666/151884801-4f29aa65-59df-4b89-bcdb-76c400f50878.png">
[octoprint-systeminfo-20220131175010.zip](https://github.com/j7126/OctoPrint-Dashboard/files/7974743/octoprint-systeminfo-20220131175010.zip)

**Comment by shakeandbake017** [comment]
I see an old post staying it's hard coded to celsius so this can close

**Comment by j7126** [comment]
This is a bug
