### ISSUE TITLE
MagicMirror 2 Module

### ISSUE THREAD

**Issue by PineappleJama** [j7126/OctoPrint-Dashboard#337]
Can the information as the dials etc be added as a MagicMirror 2 module please?

**Comment by j7126** [comment]
I have no plans of developing a MagicMirror Module any time soon. However as dashboard is just a web page, you could probably achieve what you want by using a MagicMirror module to display the page. 

For example https://github.com/AgP42/MMM-SmartWebDisplay (I have not used this or anything just found it from a quick search) or something similar to display the dashboard webpage inside of MagicMirror.

Using that module you could use a config something like this:
```javascript
modules: [
    {
        module: 'MMM-SmartWebDisplay',
        position: 'middle_center',
        config: {
            logDebug: false,
            height:"100%", // some height
            width:"100%", // some width
            updateInterval: 0,
            NextURLInterval: 0,
            displayLastUpdate: false,
            url: ["http://octopi.local/?dashboard=full#tab_plugin_dashboard"], // octoprint url
            scrolling: "no", 
        }
    },
]
```

And then you can set the visibility of each widget in octoprint dashboard settings here:
![image](https://user-images.githubusercontent.com/35882868/155977204-085a87f6-817d-4fc3-a727-77d6ac43d1b2.png)
![image](https://user-images.githubusercontent.com/35882868/155977263-1203293d-c2c9-4c26-9087-005da5179b9a.png)

You could potentially also use something like this https://github.com/shbatm/octomirror-module/.

Hopefully this helps.
