### ISSUE TITLE
[Bug]: Dashboard show CPU 0c on OrangePI_Zero2

### ISSUE THREAD

**Issue by BiOs2k** [j7126/OctoPrint-Dashboard#341]
### The problem

Dashboard show CPU 0c on OrangePI_Zero2

### Version of OctoPrint

1.7.3

### Platform

OrangePI Zero2 H616

### Operating system running OctoPrint

Ubuntu 20.04.4 LTS

### Dashboard version

Dashboard (1.19.8)

### Python version

Python 3.8

### Printer model & used firmware incl. version

Marlin 

### Browser and version of browser, operating system running browser

FireFox

### Logs and other files needed for analysis

- [X] Systeminfo Bundle (always include!) See [here](https://community.octoprint.org/t/what-is-a-systeminfo-bundle-and-how-can-i-obtain-one/29887) if you don't know where to find that.
- [x] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [x] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### File uploads & additional information

After reading many information I finally been able to fix my issue by modifing the __init__.py
Here is the code Added to make it work. if possible to add in the next release 

 elif 'cpu_thermal_zone' in thermal: #OrangePI_Zero2
 self.cpu_temp = int(round((thermal["cpu_thermal_zone"][0][1])))

**Comment by j7126** [comment]
👍
