### ISSUE TITLE
[Bug]: Minor color shift of print button & disk usage icon.

### ISSUE THREAD

**Issue by Gozania** [j7126/OctoPrint-Dashboard#344]
### The problem

1. I noticed that after a layer is complete there is a brief color shift of the print button and the disk usage icon.  I have attached photos of before layer completion & during the color shift itself.   May be difficult to see, so you may want to run a quick print to see for yourself. 

Not really a bug, but more of an observation that I am unsure if intended...

### Version of OctoPrint

1.8.0

### Platform

Raspbery Pi 4 8GB

### Operating system running OctoPrint

Octopi

### Dashboard version

1.19.8

### Python version

3

### Printer model & used firmware incl. version

Ender 3V2 : Jeyers V2.0.2h

### Browser and version of browser, operating system running browser

Firefox 100.0.2 (64 Bit)

### Logs and other files needed for analysis

- [X] Systeminfo Bundle (always include!) See [here](https://community.octoprint.org/t/what-is-a-systeminfo-bundle-and-how-can-i-obtain-one/29887) if you don't know where to find that.
- [x] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### File uploads & additional information

[octoprint-systeminfo-20220522204952.zip](https://github.com/j7126/OctoPrint-Dashboard/files/8751595/octoprint-systeminfo-20220522204952.zip)
![1Screenshot_20220522-220300_Gallery](https://user-images.githubusercontent.com/83924000/169747941-7959f490-c2a2-4fc6-a459-3a2d76ce95a4.jpg)
![2Screenshot_20220522-220318_Gallery](https://user-images.githubusercontent.com/83924000/169747944-cfb306d3-996e-4ec0-8b50-025b13c30c7d.jpg)

**Comment by j7126** [comment]
I can't seem to see this issue happening on my end.
