### ISSUE TITLE
Long file names exceed Dashboard

### ISSUE THREAD

**Issue by CWempe** [j7126/OctoPrint-Dashboard#349]
I am using long file names for my projects and the axceed the dashboard and overlap to the right.

![image](https://user-images.githubusercontent.com/1270359/173185484-accdbadd-1b3f-4f03-ada0-dfb001345845.png)

I think a solution could be to decrease the font size for too long file names.

**Comment by CWempe** [comment]
I changed some setting of the dashboard for the first time and now it looks good.

Maybe the previous settings were old. 🤷‍♂️ 

![image](https://user-images.githubusercontent.com/1270359/173185688-38cf33a5-0c22-4c9d-a850-81c9d4f5c192.png)

**Comment by CWempe** [comment]
Sorry, but I need to reopen this issue again.

When starting a new print job the issue still exists.

![image](https://user-images.githubusercontent.com/1270359/173186507-f6767472-0e48-47d5-95e4-939de32075c4.png)

But after pressing F5 to refresh the browser window it is fixed.

**Comment by j7126** [comment]
I can't seem to reproduce the issue, can you please share the exact sequence of steps you took before the issue occurred. Can you also please share you octoprint system info bundle.

**Comment by CWempe** [comment]
## Steps to reproduce

* open OctoPrint with Chrome
* Power On printer via Tasmota-MQTT Plugin
* Open last project (`.gcode`)
* See long file name

![octoprint_long_name](https://user-images.githubusercontent.com/1270359/177407829-b65bc36d-5fc5-441f-9f63-8c660a33e336.gif)

## octoprint system info bundle

[octoprint-systeminfo-20220705220354.zip](https://github.com/j7126/OctoPrint-Dashboard/files/9049241/octoprint-systeminfo-20220705220354.zip)
