### ISSUE TITLE
Add support for Libre Computer "Le Potato" Temp Sensor

### ISSUE THREAD

**Issue by SeeJayEmm** [j7126/OctoPrint-Dashboard#359]
**Is your feature request related to a problem? Please describe.**
CPU temp shows 0.

**Describe the solution you'd like**
Please add support for the temp sensor on the Le Potato board.

**Describe alternatives you've considered**
Not sure there's an alternative here other than living with it.

**Additional context**
Seems related to this conversation.
https://github.com/j7126/OctoPrint-Dashboard/issues/148

I'm running Octoprint on the Libre Computer "Le Potato" with Ubuntu 22.04 LTS.  Currently in Dashboard the CPU temp is 0.  When I run the sensors command I get:

```
scpi_sensors-isa-0000
Adapter: ISA adapter
aml_thermal:  +45.0°C
```

psutil gives a similar result.

```
>>> import psutil
>>> print(psutil.sensors_temperatures(fahrenheit=False))
{'scpi_sensors': [shwtemp(label='aml_thermal', current=45.0, high=None, critical=None)]}
```

**Comment by j7126** [comment]
I have released a new version with a fix.
