### ISSUE TITLE
[Bug]: Maybe? Tab Location

### ISSUE THREAD

**Issue by EQNish** [j7126/OctoPrint-Dashboard#374]
### The problem

Something has moved my Dashboard tab to the center of my tabs, how do I get it back to the first tab
![image](https://user-images.githubusercontent.com/84060784/216524413-2eabc4fa-c70b-4497-8b9a-261eb842f59b.png)

### Version of OctoPrint

1.8.6

### Platform

Raspberry Pi 4

### Operating system running OctoPrint

OctoPi

### Dashboard version

1.19.9

### Browser and version of browser, operating system running browser

Brave/Chrome  v1.47.186 (Jan 25, 2023)

### Logs and other files needed for analysis

- [X] Systeminfo Bundle (always include!) See [here](https://community.octoprint.org/t/what-is-a-systeminfo-bundle-and-how-can-i-obtain-one/29887) if you don't know where to find that.
- [X] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### File uploads & additional information

[octoprint-systeminfo-20230203010514.zip](https://github.com/j7126/OctoPrint-Dashboard/files/10576000/octoprint-systeminfo-20230203010514.zip)

**Comment by j7126** [comment]
There are certain plugins that can be used to re-order tabs, do you have one of these installed?

If not, I am not sure what could have caused this, but you should be able to use one of those plugins to change the order back to what you want.
