### ISSUE TITLE
Not working on latest octoprint 1.10.0rc4

### ISSUE THREAD

**Issue by tigercjn** [j7126/OctoPrint-Dashboard#403]
### The problem

Just headings shows without data.
![image](https://github.com/j7126/OctoPrint-Dashboard/assets/41408625/ea43ce07-b291-4edd-bc88-53f7c2df48f5)

### Version of OctoPrint

 1.10.0rc4

### Platform

Pi 3b+

### Operating system running OctoPrint

Octopi

### Dashboard version

1.19.10

### Printer model & used firmware incl. version

snapmaker 2.0

### Browser and version of browser, operating system running browser

Chrome Version 123.0.6312.106 (Official Build) (64-bit)

### Logs and other files needed for analysis

- [X] Systeminfo Bundle (always include!) See [here](https://community.octoprint.org/t/what-is-a-systeminfo-bundle-and-how-can-i-obtain-one/29887) if you don't know where to find that.
- [X] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### File uploads & additional information

![image](https://github.com/j7126/OctoPrint-Dashboard/assets/41408625/6532ade9-8994-40fe-8c9e-891d7b6f1e52)
[octoprint-systeminfo-20240409120222.zip](https://github.com/j7126/OctoPrint-Dashboard/files/14912532/octoprint-systeminfo-20240409120222.zip)

**Comment by jneilliii** [comment]
To add to this issue, it appears to be related to the printer profile binding.

![image](https://github.com/j7126/OctoPrint-Dashboard/assets/5249455/043b7bb1-8531-43e1-b9ba-469b6b0c7c5e)

**Comment by j7126** [comment]
Yeah it appears that currentProfileData() is undefined for some reason

**Comment by j7126** [comment]
fixed in latest release 1.19.11
