### ISSUE TITLE
[Suggestion] Easier bug/support system 

### ISSUE THREAD

**Issue by den1251** [j7126/OctoPrint-Dashboard#411]
I think the current bug/support system is overcomplicated, including logs for just a simple question is way too much.

I would like a discord server or something like that to be present, so It will be easier to ask simple questions.

**Comment by j7126** [comment]
The reason the bug report template says to include logs for all issues, is that many people think they are reporting a simple issue, or think that logs are not needed for some reason, and then don't include them, and it ends up being impossible to solve without the logs. I don't want to have to ask for logs for every issue. You can still open an issue without including that if you really want to though.

In terms of discord, I am in the official OctoPrint discord server, so feel free to @ me there in the #support-plugins channel.
