### ISSUE TITLE
Ability to scroll Layer Durations

### ISSUE THREAD

**Issue by LMS0815** [j7126/OctoPrint-Dashboard#73]
If possible add the ability to scroll the **Layer Durations** graph for big jobs...
![Anmerkung 2019-10-05 184506](https://user-images.githubusercontent.com/8235214/66258004-4e8a9780-e7a0-11e9-964b-9d4c2c2be26a.png)

**Comment by StefanCohen** [comment]
I at least need to find a better algorithm for reducing the number of X labels :)

I use [chartist.js](https://gionkunz.github.io/chartist-js/) for the graph. It is possible that scrolling & zooming is supported but I haven't looked yet.

**Comment by StefanCohen** [comment]
I just checked and chartist.js doesn't provide a method to scroll the chart. I'll leave this one open until I find a better way to reduce the X axis labels.

**Comment by StefanCohen** [comment]
The current algorithm to remove labels based on the number of labels is defined [here](https://github.com/StefanCohen/OctoPrint-Dashboard/blob/e601b9edd5b0663170be5f2ae9405ce716d7c0ab/octoprint_dashboard/static/js/dashboard.js#L382-L389)

We'll need to find a method to keep it at a maximum of 40 labels but I can't figure out the math to do so. I welcome any suggestions.

**Comment by Willmac16** [comment]
I know of a pretty simple way to allow for scrolling: increasing the width of the graph based off of the number of layers and correctly setting the overflow attributes for the div the graph lives in. This would require changes to the label interpolation algorithm to ensure even spacing, and it might make sense to add an option to enable/disable layer view scrolling.

**Comment by Willmac16** [comment]
I also wrote label interpolation that does equal spacing maxing out at 40 labels.

**Comment by StefanCohen** [comment]
Cool. I will review the PR. Thanks!

**Comment by StefanCohen** [comment]
That PR looks really good. I'm including this in v1.14

**Comment by Haasje** [comment]
Is there a way to disable the scrollbar? I think it looks really ugly in the theme I'm using and I just want to have a quick overview of the layertimes without having to scroll thru them.

**Comment by StefanCohen** [comment]
Not yet. I still haven't figured out how to approach the settings for this.

**Comment by Willmac16** [comment]
Does it make more sense to implement a plugin wide setting for this or just a simple toggle button in the dashboard?

**Comment by ranger81** [comment]
Hi there,
I have another suggestion for the layer duration graph. Is there a possibility to include an "auto-scroll" to the most right position? For longer prints, the layer duration graph only shows the beginning of the print. Then you need to manually scroll to the right most end to see the lastest durations. I think it would be beneficial to automatically scroll to the latest durations.
What do you think?

**Comment by Willmac16** [comment]
Do you think it would be better to have an option that only displays the last 80 or so layers instead.

**Comment by Willmac16** [comment]
A layer duration graph scrolling option has been added.
